/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: hash.proto */

#ifndef PROTOBUF_C_hash_2eproto__INCLUDED
#define PROTOBUF_C_hash_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _HelloRequest HelloRequest;


/* --- enums --- */


/* --- messages --- */

struct  _HelloRequest
{
  ProtobufCMessage base;
  char *name;
};
#define HELLO_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hello_request__descriptor) \
    , NULL }


/* HelloRequest methods */
void   hello_request__init
                     (HelloRequest         *message);
size_t hello_request__get_packed_size
                     (const HelloRequest   *message);
size_t hello_request__pack
                     (const HelloRequest   *message,
                      uint8_t             *out);
size_t hello_request__pack_to_buffer
                     (const HelloRequest   *message,
                      ProtobufCBuffer     *buffer);
HelloRequest *
       hello_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hello_request__free_unpacked
                     (HelloRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*HelloRequest_Closure)
                 (const HelloRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hello_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_hash_2eproto__INCLUDED */
